name: flutter_amplitude
description: Flutter pluging for Amplitude SDK
version: 0.0.1
author: Miguel Catalan<miguel.catalan@eval.ly>
homepage: https://github.com/Evally/flutter_amplitude

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: ly.eval.flutteramplitude
    pluginClass: FlutterAmplitudePlugin
